import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const SERVER_DIR = path.dirname(fileURLToPath(import.meta.url));
const TRANSCRIBE_MJS = path.resolve(SERVER_DIR, '..', 'transcribe.mjs');
const SAFE_SLUG = /^[A-Za-z0-9._-]+$/;

export function createEpisodeStore({ root, raw, cleaned }) {
  function dir(slug) {
    return path.join(raw, slug);
  }

  function scriptFor(episodeDir) {
    return `#!/usr/bin/env bash
# Generated by podcast-to-essay web. Pipeline: split -> Step Plan ASR -> merge.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
node "${TRANSCRIBE_MJS}" "$HERE"
`;
  }

  async function writeScript(episodeDir) {
    const script = path.join(episodeDir, 'transcribe.sh');
    await fsp.writeFile(script, scriptFor(episodeDir), 'utf8');
    await fsp.chmod(script, 0o755);
    return script;
  }

  async function readJSON(file) {
    try { return JSON.parse(await fsp.readFile(file, 'utf8')); }
    catch { return null; }
  }

  async function readMeta(episodeDir) {
    return readJSON(path.join(episodeDir, 'source-meta.json'));
  }

  async function writeMeta(episodeDir, meta) {
    const dest = path.join(episodeDir, 'source-meta.json');
    const tmp = `${dest}.${process.pid}.tmp`;
    await fsp.writeFile(tmp, JSON.stringify(meta, null, 2), 'utf8');
    await fsp.rename(tmp, dest);
  }

  async function clearSourceFiles(episodeDir) {
    let files = [];
    try { files = await fsp.readdir(episodeDir); } catch { return; }
    for (const name of files) {
      if (/^source\.[A-Za-z0-9]+$/.test(name)) await fsp.rm(path.join(episodeDir, name), { force: true });
    }
  }

  async function titlesFromIndex() {
    let md = '';
    try { md = await fsp.readFile(path.join(root, 'INDEX.md'), 'utf8'); } catch { return {}; }
    const map = {};
    for (const line of md.split('\n')) {
      if (!line.startsWith('|')) continue;
      const cells = line.split('|').map((cell) => cell.trim());
      const slug = cells[1];
      const title = cells[2];
      const duration = cells[3];
      if (!slug || slug === 'slug' || /^-+$/.test(slug) || !SAFE_SLUG.test(slug)) continue;
      map[slug] = {
        title: title && title !== '标题' ? title : null,
        duration: duration && /^\d/.test(duration) ? duration : null,
      };
    }
    return map;
  }

  async function list(jobs = []) {
    const titles = await titlesFromIndex();
    let entries = [];
    try { entries = await fsp.readdir(raw, { withFileTypes: true }); } catch { return []; }
    const out = [];
    for (const entry of entries.filter((item) => item.isDirectory())) {
      const slug = entry.name;
      const episodeDir = dir(slug);
      let files = [];
      try { files = await fsp.readdir(episodeDir); } catch { files = []; }
      const source = files.find((name) => /^source\.[A-Za-z0-9]+$/.test(name)) || null;
      const hasRaw = files.includes('asr_raw.txt');
      const hasSrt = files.includes('asr_raw.srt');
      let chunkFiles = files.filter((name) => /^chunk_\d+\.mp3$/.test(name));
      let completedChunkFiles = files.filter((name) => /^chunk_\d+\.txt$/.test(name));
      if (chunkFiles.length === 0) {
        try {
          const nested = await fsp.readdir(path.join(episodeDir, 'chunks'));
          chunkFiles = nested.filter((name) => /^chunk_\d+\.mp3$/.test(name));
          completedChunkFiles = nested.filter((name) => /^chunk_\d+\.txt$/.test(name));
        } catch { /* no chunk directory yet */ }
      }
      let cleanedAt = null;
      try { cleanedAt = (await fsp.stat(path.join(cleaned, `${slug}.md`))).mtimeMs; } catch { /* no article */ }
      const status = cleanedAt ? 'cleaned' : !source ? 'empty' : !hasRaw ? 'uploaded' : 'transcribed';
      const index = titles[slug] || {};
      const disk = await readMeta(episodeDir);
      const article = await readJSON(path.join(episodeDir, 'article-meta.json'));
      const savedState = await readJSON(path.join(episodeDir, 'transcription-state.json'));
      const related = jobs
        .filter((job) => job.type === 'transcription' && job.episodeSlug === slug)
        .sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt)));
      const active = related.find((job) => job.state === 'running' || job.state === 'paused' || job.state === 'queued');
      const interrupted = related.find((job) => job.state === 'interrupted');
      const failedJob = related.find((job) => job.state === 'failed');
      let transcription = null;
      if (active) transcription = { state: active.state === 'paused' ? 'paused' : 'running', error: null, jobId: active.id, diagnosticId: null };
      else if (interrupted && !hasRaw) {
        transcription = {
          state: 'interrupted',
          error: '任务因服务重启中断，已完成内容仍在，可以继续。',
          jobId: interrupted.id,
          diagnosticId: null,
        };
      } else if (failedJob || savedState?.state === 'failed') {
        transcription = {
          state: 'failed',
          error: failedJob?.error?.userMessage || savedState?.error || '转录未完成，已完成的片段已保留。',
          jobId: failedJob?.id || null,
          diagnosticId: failedJob?.error?.diagnosticId || null,
        };
      }
      out.push({
        slug,
        title: index.title || disk?.title || disk?.originalName || null,
        duration: index.duration || null,
        source,
        sourceUrl: disk?.url || null,
        originalName: disk?.originalName || null,
        hasRaw,
        hasSrt,
        chunkCount: chunkFiles.length,
        completedChunks: completedChunkFiles.length,
        transcription,
        cleaned: !!cleanedAt,
        cleanedAt,
        article,
        status,
      });
    }
    out.sort((a, b) => b.slug.localeCompare(a.slug));
    return out;
  }

  async function ownerOf(slug) {
    const meta = await readJSON(path.join(dir(slug), 'owner.json'));
    return meta?.owner || 'user';
  }

  async function canAccess(slug, viewer) {
    if (viewer.owner) return true;
    return (await ownerOf(slug)) === `guest:${viewer.guestId}`;
  }

  function todayStamp() {
    const now = new Date();
    const p = (n) => String(n).padStart(2, '0');
    return `${now.getFullYear()}-${p(now.getMonth() + 1)}-${p(now.getDate())}`;
  }

  function slugBase(link) {
    const bv = String(link).match(/(BV[\w]{10})/i)?.[1];
    return `${todayStamp()}-${bv ? bv.toLowerCase() : 'link'}`;
  }

  const pendingSlugs = new Set();
  let slugTail = Promise.resolve();

  function allocateSlug(link, reserved = []) {
    const run = slugTail.then(async () => {
      const taken = new Set([...reserved, ...pendingSlugs]);
      try {
        for (const name of await fsp.readdir(raw)) taken.add(name);
      } catch { /* raw may not exist yet */ }
      const base = slugBase(link);
      let slug = base;
      let n = 2;
      while (taken.has(slug)) slug = `${base}-${n++}`;
      pendingSlugs.add(slug);
      return slug;
    });
    slugTail = run.then(() => {}, () => {});
    return run;
  }

  async function create(slug, ownerTag) {
    const episodeDir = dir(slug);
    await fsp.mkdir(episodeDir, { recursive: true });
    await writeScript(episodeDir);
    if (ownerTag) {
      await fsp.writeFile(path.join(episodeDir, 'owner.json'), JSON.stringify({ owner: ownerTag }, null, 2), 'utf8');
    }
    return slug;
  }

  async function setTitle(slug, title) {
    const episodeDir = dir(slug);
    await writeMeta(episodeDir, { ...(await readMeta(episodeDir) || {}), title });
  }

  async function remove(slug) {
    await fsp.rm(dir(slug), { recursive: true, force: true });
    await fsp.rm(path.join(cleaned, `${slug}.md`), { force: true });
  }

  async function saveAudio(slug, { filename, originalName, stream, maxBytes, blocked }) {
    const episodeDir = dir(slug);
    const ext = path.extname(filename).toLowerCase();
    if (blocked(ext)) {
      const err = new Error('这不是音轨或视频');
      err.status = 400;
      throw err;
    }
    await clearSourceFiles(episodeDir);
    const dest = path.join(episodeDir, `source${ext || '.bin'}`);
    await writeLimited(stream, dest, maxBytes);
    await writeMeta(episodeDir, {
      originalName: originalName || path.basename(filename),
      url: null,
      title: originalName ? originalName.replace(/\.[^.]+$/, '') : null,
    });
    return path.basename(dest);
  }

  async function readTranscript(slug, type) {
    const file = type === 'srt'
      ? path.join(dir(slug), 'asr_raw.srt')
      : type === 'cleaned'
        ? path.join(cleaned, `${slug}.md`)
        : path.join(dir(slug), 'asr_raw.txt');
    try { return await fsp.readFile(file, 'utf8'); }
    catch { return null; }
  }

  async function writeArticle(slug, text, meta) {
    const out = path.join(cleaned, `${slug}.md`);
    const metaOut = path.join(dir(slug), 'article-meta.json');
    const tempId = randomUUID();
    const outTemp = `${out}.${tempId}.tmp`;
    const metaTemp = `${metaOut}.${tempId}.tmp`;
    await Promise.all([
      fsp.writeFile(outTemp, `${text}\n`, 'utf8'),
      fsp.writeFile(metaTemp, `${JSON.stringify(meta, null, 2)}\n`, 'utf8'),
    ]);
    await fsp.rename(metaTemp, metaOut);
    await fsp.rename(outTemp, out);
  }

  async function publishIngest({ slug, stageDir, owner, url, title, file }) {
    await writeMeta(stageDir, { url, title: title || null, originalName: title || file });
    await writeScript(stageDir);
    await fsp.writeFile(path.join(stageDir, 'owner.json'), JSON.stringify({ owner }, null, 2), 'utf8');
    const dest = dir(slug);
    if (fs.existsSync(dest)) throw Object.assign(new Error('episode exists'), { code: 'internal_error' });
    await fsp.rename(stageDir, dest);
  }

  async function adoptSource(slug, stageDir, { url, title, file }) {
    const episodeDir = dir(slug);
    await clearSourceFiles(episodeDir);
    await fsp.rename(path.join(stageDir, file), path.join(episodeDir, file));
    await writeMeta(episodeDir, { url, title: title || null, originalName: title || file });
    await fsp.rm(stageDir, { recursive: true, force: true });
  }

  function writtenDuringJob(mtimeMs, startedAt) {
    const start = Date.parse(startedAt || '');
    return Number.isFinite(start) && mtimeMs >= start;
  }

  async function fileFromThisJob(file, startedAt) {
    try {
      const stat = await fsp.stat(file);
      return stat.isFile() && stat.size > 0 && writtenDuringJob(stat.mtimeMs, startedAt);
    } catch {
      return false;
    }
  }

  async function hasSource(slug) {
    try {
      const files = await fsp.readdir(dir(slug));
      return files.some((name) => /^source\.[A-Za-z0-9]+$/.test(name));
    } catch {
      return false;
    }
  }

  async function hasDurableResult(job) {
    if (job.type === 'ingest') {
      const episodeDir = dir(job.episodeSlug);
      let names = [];
      try { names = await fsp.readdir(episodeDir); } catch { return false; }
      const mediaName = names.find((name) => /^source\.[A-Za-z0-9]+$/.test(name));
      if (!mediaName) return false;
      const mediaOk = await fileFromThisJob(path.join(episodeDir, mediaName), job.startedAt);
      const metaOk = await fileFromThisJob(path.join(episodeDir, 'source-meta.json'), job.startedAt);
      if (!mediaOk || !metaOk) return false;
      const meta = await readMeta(episodeDir);
      return meta?.url === job.sourceUrl;
    }
    if (job.type === 'transcription') return fileFromThisJob(path.join(dir(job.episodeSlug), 'asr_raw.txt'), job.startedAt);
    if (job.type === 'article') return fileFromThisJob(path.join(cleaned, `${job.episodeSlug}.md`), job.startedAt);
    return false;
  }

  async function writeTranscriptionState(slug, state, error = null) {
    await fsp.writeFile(
      path.join(dir(slug), 'transcription-state.json'),
      JSON.stringify({ state, error, updatedAt: Date.now() }),
      'utf8',
    ).catch(() => {});
  }

  return {
    raw,
    cleaned,
    dir,
    safeSlug: SAFE_SLUG,
    exists: (slug) => fs.existsSync(dir(slug)),
    list,
    ownerOf,
    canAccess,
    allocateSlug,
    create,
    setTitle,
    remove,
    saveAudio,
    readMeta,
    writeMeta,
    clearSourceFiles,
    readTranscript,
    writeArticle,
    publishIngest,
    adoptSource,
    hasSource,
    hasDurableResult,
    writeScript,
    writeTranscriptionState,
    titlesFromIndex,
  };
}

function writeLimited(stream, dest, maxBytes) {
  return new Promise((resolve, reject) => {
    const ws = fs.createWriteStream(dest);
    let seen = 0;
    let failed = false;
    const fail = (err) => {
      if (failed) return;
      failed = true;
      stream.unpipe(ws);
      ws.destroy();
      stream.destroy?.();
      fsp.rm(dest, { force: true }).finally(() => reject(err));
    };
    stream.on('data', (chunk) => {
      seen += chunk.length;
      if (seen > maxBytes) fail(Object.assign(new Error('文件太大'), { code: 'file_too_large' }));
    });
    stream.pipe(ws);
    ws.on('finish', () => { if (!failed) resolve(); });
    ws.on('error', fail);
    stream.on('error', fail);
  });
}
