#!/usr/bin/env bash
# Generated by podcast-to-essay web. Pipeline: split -> Step Plan ASR -> merge.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
node "$HERE/../../web/server/transcribe.mjs" "$HERE"
