// Podcast-to-Essay — Node backend (zero external dependencies).
//
// Responsibilities:
//  - Episode management: list / create / delete under <ROOT>/raw/<slug>/
//  - Audio upload: save uploaded file as raw/<slug>/source.<ext>
//  - Transcribe: spawn the per-episode transcribe.sh (ffmpeg + Stepfun ASR +
//    merge) and stream logs back over SSE
//  - Transcript read: serve raw/<slug>/asr_raw.{txt,srt} and cleaned/<slug>.md
//  - Clean: heuristic LLM-style cleanup of asr_raw.txt -> cleaned/<slug>.md
//    (the "Agent" hook — swap the cleanup step for a real model call later)
//
// In dev it only answers /api (Vite serves the frontend). In prod it also
// serves the built assets from ../dist.

import http from 'node:http';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WEB_DIR = path.resolve(__dirname, '..');
const ROOT = path.resolve(__dirname, '..', '..'); // podcast-to-essay
const RAW = path.join(ROOT, 'raw');
const CLEANED = path.join(ROOT, 'cleaned');
const DIST = path.join(WEB_DIR, 'dist');

const PORT = Number(process.env.PORT || 8787);
const IS_DEV = process.env.IS_DEV === '1';
const HOME = process.env.HOME || '';
const ENGINE = process.env.ASR_SKILL_DIR || path.join(HOME, '.claude', 'skills', 'asr-transcript-refinement');

fs.mkdirSync(RAW, { recursive: true });
fs.mkdirSync(CLEANED, { recursive: true });

const SAFE_SLUG = /^[A-Za-z0-9._-]+$/;

// ---- 混元 (Hunyuan) OpenAI-compatible API ----
const HUNYUAN_BASE = 'https://api.hunyuan.cloud.tencent.com/v1';
const HUNYUAN_MODEL = process.env.HUNYUAN_MODEL || 'hunyuan-lite';
const HUNYUAN_KEY = process.env.HUNYUAN_API_KEY || '';
const AI_AVAILABLE = !!HUNYUAN_KEY; // true once `export HUNYUAN_API_KEY=sk-...` is set
if (!AI_AVAILABLE) console.log('[server] ⚠ HUNYUAN_API_KEY not set — will use heuristic cleanup (offline mode).');

// ---- per-episode transcribe.sh template (engine path injected at create) ----
function transcribeTemplate(skillDir) {
  return `#!/usr/bin/env bash
# Generated by podcast-to-essay web. Pipeline: split -> Stepfun ASR -> merge.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SKILL="${skillDir}"
TRANSCRIBE="\${SKILL}/scripts/transcribe_stepfun.py"
MERGE="\${SKILL}/scripts/merge.py"

if [[ -z "\${STEP_API_KEY:-}" ]]; then
  echo "❌ STEP_API_KEY not set. export STEP_API_KEY=sk-... first" >&2
  exit 1
fi

SRC=$(ls source.* 2>/dev/null | head -1)
if [[ -z "\$SRC" ]]; then echo "❌ no source.* audio found in $(pwd)" >&2; exit 1; fi

echo "=== [1/3] Splitting \$SRC into 3-min chunks ==="
mkdir -p chunks asr_raw
ffmpeg -y -i "\$SRC" -ac 1 -ar 16000 -c:a libmp3lame -b:a 64k \\
  -f segment -segment_time 180 -reset_timestamps 1 \\
  chunks/chunk_%03d.mp3 2>/dev/null
N=$(ls -1 chunks/chunk_*.mp3 | wc -l | tr -d ' ')
echo "  -> \$N chunks written"

echo "=== [2/3] Stepfun ASR per chunk ==="
for mp3 in chunks/chunk_*.mp3; do
  base="\${mp3%.mp3}"
  if [[ -s "\${base}.txt" ]]; then echo "  [skip] \$(basename "\$base")"; continue; fi
  echo "  -> \$(basename "\$mp3")"
  python3 "\$TRANSCRIBE" "\$mp3" "\$base" 2>&1 | tail -3
done

echo "=== [3/3] Merging into asr_raw.txt ==="
python3 "\$MERGE" chunks asr_raw.srt asr_raw.txt
echo "✅ Done -> \$(pwd)/asr_raw.txt"
`;
}

// ----------------------------- helpers --------------------------------------
async function listEpisodes() {
  let entries = [];
  try {
    entries = await fsp.readdir(RAW, { withFileTypes: true });
  } catch {
    return [];
  }
  const dirs = entries.filter((e) => e.isDirectory()).map((e) => e.name);
  const out = [];
  for (const slug of dirs) {
    const dir = path.join(RAW, slug);
    let files = [];
    try { files = await fsp.readdir(dir); } catch { files = []; }
    const source = files.find((f) => /^source\./.test(f)) || null;
    const hasRaw = files.includes('asr_raw.txt');
    const hasSrt = files.includes('asr_raw.srt');
    const chunkCount = files.filter((f) => /^chunk_\d+\.mp3$/.test(f)).length;
    let cleanedAt = null;
    try { const s = await fsp.stat(path.join(CLEANED, slug + '.md')); cleanedAt = s.mtimeMs; } catch {}
    const status = !source ? 'empty' : !hasRaw ? 'uploaded' : !cleanedAt ? 'transcribed' : 'cleaned';
    out.push({ slug, source, hasRaw, hasSrt, chunkCount, cleaned: !!cleanedAt, cleanedAt, status });
  }
  out.sort((a, b) => b.slug.localeCompare(a.slug));
  return out;
}

// ---- AI cleanup: Hunyuan (Tencent 混元) OpenAI-compatible API --------------
// When HUNYUAN_API_KEY is set, this is the primary cleanup path.
// Falls back to heuristicCleanup() when key is absent or API fails.
//
// Token budget: 混元免费额度 100万 tokens；长文本自动按 ~100 行切块，
// 逐块调用 Hunyuan，保持说话人上下文。

const AI_SYSTEM_PROMPT = `你是播客转录稿的清洗助手。给定一段带时间戳的 ASR 原始文本，请按以下规则清洗并输出：

规则：
- 删除所有 [HH:MM:SS,mmm] 时间戳。
- 修正明显的 ASR 识别错字（如“混元”→“混元”保持原样，真正的错字才改）。
- 保留原始的说话人标签（如 Speaker 0/1、人名），不要改写或重命名。
- 将同一说话人的连续发言合并为自然段落，换说话人时分段。
- 不要添加任何标题（H1/H2/H3）、不要添加分析或总结，只输出清洗后的纯文本。
- 输出格式：每个段落以「**说话人：** 内容」开头，段落之间空一行。`;

// --- 切块：按行数分片，保持文本可在一个 API 调用内处理 ---
function chunkTranscript(rawText, chunkLines = 100) {
  const lines = rawText.split('\n');
  const chunks = [];
  for (let i = 0; i < lines.length; i += chunkLines) {
    chunks.push(lines.slice(i, i + chunkLines).join('\n'));
  }
  return chunks;
}

// --- 调用混元 Chat Completions API (OpenAI 兼容) ---
async function callHunyuan(systemPrompt, userMessage) {
  const res = await fetch(`${HUNYUAN_BASE}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${HUNYUAN_KEY}`,
    },
    body: JSON.stringify({
      model: HUNYUAN_MODEL,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userMessage },
      ],
      temperature: 0.1,
      max_tokens: 8192,
    }),
  });
  if (!res.ok) {
    const errBody = await res.text().catch(() => '');
    throw new Error(`混元 API 返回 ${res.status}: ${errBody.slice(0, 300)}`);
  }
  const data = await res.json();
  return data.choices?.[0]?.message?.content || '';
}

// --- AI 清洗主流程：切块 → 逐块调混元 → 拼接 ---
async function cleanWithAI(rawText) {
  const chunks = chunkTranscript(rawText, 100);
  const results = [];
  for (let i = 0; i < chunks.length; i++) {
    const content = await callHunyuan(AI_SYSTEM_PROMPT, chunks[i]);
    if (content) results.push(content);
  }
  return results.join('\n\n');
}

// --- 启发式清洗 (fallback)：去掉时间戳、按说话人合并段落 ---
function heuristicCleanup(rawText) {
  const lines = rawText.split('\n');
  const paras = [];
  let curSpeaker = null;
  let buf = [];
  const re = /^\[\d{2}:\d{2}:\d{2},\d{3}\]\s*(.*?):\s*(.*)$/;
  for (const line of lines) {
    const m = line.match(re);
    if (!m) {
      if (line.trim()) { buf.push(line.trim()); }
      continue;
    }
    const speaker = m[1].trim();
    const text = m[2].trim();
    if (speaker !== curSpeaker) {
      if (buf.length) paras.push({ speaker: curSpeaker, text: buf.join(' ') });
      curSpeaker = speaker;
      buf = [text];
    } else {
      buf.push(text);
    }
  }
  if (buf.length) paras.push({ speaker: curSpeaker, text: buf.join(' ') });
  const body = paras
    .map((p) => (p.speaker ? `**${p.speaker}：** ${p.text}` : p.text))
    .join('\n\n');
  return body + '\n';
}

function sendJSON(res, code, obj) {
  const data = JSON.stringify(obj);
  res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8', 'Access-Control-Allow-Origin': '*' });
  res.end(data);
}

function readFileSafe(p) {
  return fsp.readFile(p, 'utf8').catch(() => null);
}

// ----------------------------- routing ---------------------------------------
async function handleApi(req, res, url) {
  const parts = url.pathname.split('/').filter(Boolean); // ['api', ...]
  const method = req.method;

  // GET /api/health
  if (method === 'GET' && parts[1] === 'health') {
    return sendJSON(res, 200, { ok: true, engine: ENGINE, root: ROOT, hunyuan: AI_AVAILABLE, model: HUNYUAN_MODEL });
  }

  // GET /api/episodes
  if (method === 'GET' && parts[1] === 'episodes' && parts.length === 2) {
    return sendJSON(res, 200, { episodes: await listEpisodes() });
  }

  // POST /api/episodes  { slug }
  if (method === 'POST' && parts[1] === 'episodes' && parts.length === 2) {
    const body = await readBody(req);
    const slug = (body.slug || '').toString().trim();
    if (!SAFE_SLUG.test(slug)) return sendJSON(res, 400, { error: 'invalid slug' });
    const dir = path.join(RAW, slug);
    if (fs.existsSync(dir)) return sendJSON(res, 409, { error: 'episode exists' });
    await fsp.mkdir(dir, { recursive: true });
    await fsp.writeFile(path.join(dir, 'transcribe.sh'), transcribeTemplate(ENGINE), 'utf8');
    await fsp.chmod(path.join(dir, 'transcribe.sh'), 0o755);
    return sendJSON(res, 201, { ok: true, slug });
  }

  // /api/episodes/:slug/...  (length >= 4)
  if (parts[1] === 'episodes' && parts.length >= 3) {
    const slug = parts[2];
    if (!SAFE_SLUG.test(slug)) return sendJSON(res, 400, { error: 'invalid slug' });
    const dir = path.join(RAW, slug);

    // DELETE /api/episodes/:slug
    if (method === 'DELETE' && parts.length === 3) {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'not found' });
      await fsp.rm(dir, { recursive: true, force: true });
      return sendJSON(res, 200, { ok: true });
    }

    // POST /api/episodes/:slug/audio   (raw bytes; filename in x-filename)
    if (method === 'POST' && parts[3] === 'audio') {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      const fname = (req.headers['x-filename'] || 'source.mp3').toString();
      const ext = path.extname(fname) || '.mp3';
      const dest = path.join(dir, 'source' + ext);
      await writeStreamToFile(req, dest);
      return sendJSON(res, 200, { ok: true, file: path.basename(dest) });
    }

    // POST /api/episodes/:slug/transcribe  -> SSE log stream
    if (method === 'POST' && parts[3] === 'transcribe') {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      const script = path.join(dir, 'transcribe.sh');
      if (!fs.existsSync(script)) {
        await fsp.writeFile(script, transcribeTemplate(ENGINE), 'utf8');
        await fsp.chmod(script, 0o755);
      }
      return streamTranscribe(res, script, dir);
    }

    // GET /api/episodes/:slug/transcript?type=raw|srt|cleaned
    if (method === 'GET' && parts[3] === 'transcript') {
      const type = url.searchParams.get('type') || 'raw';
      let p;
      if (type === 'srt') p = path.join(dir, 'asr_raw.srt');
      else if (type === 'cleaned') p = path.join(CLEANED, slug + '.md');
      else p = path.join(dir, 'asr_raw.txt');
      const text = await readFileSafe(p);
      if (text === null) return sendJSON(res, 404, { error: 'not found', type });
      res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8', 'Access-Control-Allow-Origin': '*' });
      return res.end(text);
    }

    // POST /api/episodes/:slug/clean  （?mode=ai|heuristic，默认：有 Key 用 AI，否则 heuristic）
    if (method === 'POST' && parts[3] === 'clean') {
      const rawText = await readFileSafe(path.join(dir, 'asr_raw.txt'));
      if (rawText === null) return sendJSON(res, 404, { error: 'no asr_raw.txt' });
      const mode = url.searchParams.get('mode') || (AI_AVAILABLE ? 'ai' : 'heuristic');
      let cleanText, methodUsed;
      if (mode === 'ai' && AI_AVAILABLE) {
        try {
          cleanText = await cleanWithAI(rawText);
          methodUsed = 'ai';
        } catch (err) {
          console.error('[server] Hunyuan cleanup failed:', err.message);
          cleanText = heuristicCleanup(rawText);
          methodUsed = 'heuristic (ai fallback)';
        }
      } else {
        cleanText = heuristicCleanup(rawText);
        methodUsed = 'heuristic';
      }
      const md = `# ${slug}\n\n${cleanText}`;
      const out = path.join(CLEANED, slug + '.md');
      await fsp.writeFile(out, md, 'utf8');
      return sendJSON(res, 200, { ok: true, file: out, method: methodUsed });
    }
  }

  return sendJSON(res, 404, { error: 'not found' });
}

function streamTranscribe(res, script, cwd) {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    'Access-Control-Allow-Origin': '*',
  });
  const child = spawn('bash', [script], {
    cwd,
    env: { ...process.env },
  });
  let closed = false; // per-connection guard (must NOT be shared across requests)
  const emit = (event, data) => {
    res.write(`event: ${event}\n`);
    res.write(`data: ${data}\n\n`);
  };
  const onData = (buf) => {
    for (const line of buf.toString().split('\n')) {
      if (line.length) emit('log', line);
    }
  };
  child.stdout.on('data', onData);
  child.stderr.on('data', onData);
  const finish = (code) => {
    if (closed) return;
    closed = true;
    emit('done', String(code ?? 1));
    res.end();
  };
  child.on('exit', (code) => finish(code ?? 1));
  child.on('error', (err) => {
    emit('log', '❌ ' + err.message);
    finish(1);
  });
  res.on('close', () => {
    if (closed) return;
    closed = true;
    try { child.kill(); } catch {}
  });
}

function readBody(req) {
  return new Promise((resolve) => {
    let data = '';
    req.on('data', (c) => (data += c));
    req.on('end', () => {
      try { resolve(JSON.parse(data || '{}')); } catch { resolve({}); }
    });
  });
}

function writeStreamToFile(stream, dest) {
  return new Promise((resolve, reject) => {
    const ws = fs.createWriteStream(dest);
    stream.pipe(ws);
    ws.on('finish', resolve);
    ws.on('error', reject);
    stream.on('error', reject);
  });
}

// ----------------------------- static (prod) --------------------------------
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
};

function serveStatic(req, res, url) {
  let rel = decodeURIComponent(url.pathname);
  if (rel === '/') rel = '/index.html';
  const file = path.join(DIST, rel);
  if (!file.startsWith(DIST) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
    // SPA fallback
    const idx = path.join(DIST, 'index.html');
    if (fs.existsSync(idx)) {
      res.writeHead(200, { 'Content-Type': MIME['.html'] });
      return res.end(fs.readFileSync(idx));
    }
    return sendJSON(res, 404, { error: 'frontend not built; run `npm run build`' });
  }
  const ext = path.extname(file);
  res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
  res.end(fs.readFileSync(file));
}

// ----------------------------- server ---------------------------------------
const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, `http://localhost:${PORT}`);
    if (url.pathname.startsWith('/api/') || url.pathname === '/api') {
      await handleApi(req, res, url);
    } else if (!IS_DEV && fs.existsSync(DIST)) {
      serveStatic(req, res, url);
    } else {
      sendJSON(res, 404, { error: 'unknown route', hint: 'dev: use Vite on :5173; prod: build first' });
    }
  } catch (err) {
    sendJSON(res, 500, { error: err.message });
  }
});

server.listen(PORT, () => {
  console.log(`[server] podcast-to-essay backend on http://localhost:${PORT}`);
  console.log(`[server] root=${ROOT}`);
  console.log(`[server] engine=${ENGINE}`);
});
