// Podcast-to-Essay — Node backend (zero external dependencies).
//
// Responsibilities:
//  - Episode management: list / create / delete under <ROOT>/raw/<slug>/
//  - Audio upload: save uploaded file as raw/<slug>/source.<ext>
//  - Transcribe: spawn the per-episode transcribe.sh (ffmpeg + Step Plan ASR +
//    merge) and stream logs back over SSE
//  - Transcript read: serve raw/<slug>/asr_raw.{txt,srt} and cleaned/<slug>.md
//  - Clean: heuristic LLM-style cleanup of asr_raw.txt -> cleaned/<slug>.md
//    (the "Agent" hook — swap the cleanup step for a real model call later)
//
// In dev it only answers /api (Vite serves the frontend). In prod it also
// serves the built assets from ../dist.

import http from 'node:http';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { parseEnv } from 'node:util';
import {
  BLOCK_EXT,
  assertPublicHttpUrl,
  clearSourceFiles,
  extFromName,
  ingestUrl,
  readMeta,
  writeMeta,
} from './ingest.mjs';
import { articleConfig, generateArticle } from './article.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WEB_DIR = path.resolve(__dirname, '..');
const ROOT = path.resolve(__dirname, '..', '..'); // podcast-to-essay
const RAW = path.join(ROOT, 'raw');
const CLEANED = path.join(ROOT, 'cleaned');
const INGESTS = path.join(ROOT, '.ingests');
const DIST = path.join(WEB_DIR, 'dist');

try {
  Object.assign(process.env, parseEnv(fs.readFileSync(path.join(ROOT, '.env.local'), 'utf8')));
} catch {}

const PORT = Number(process.env.PORT || 8787);
const IS_DEV = process.env.IS_DEV === '1';
const HOME = process.env.HOME || '';
const TRANSCRIPTIONS = new Map();

fs.mkdirSync(RAW, { recursive: true });
fs.mkdirSync(CLEANED, { recursive: true });
fs.mkdirSync(INGESTS, { recursive: true });

const SAFE_SLUG = /^[A-Za-z0-9._-]+$/;

let articleEngine = null;
try {
  const { model } = articleConfig();
  articleEngine = { provider: 'stepfun-token-plan', model };
} catch {}

// ---- per-episode transcribe.sh template (engine path injected at create) ----
function transcribeTemplate() {
  return `#!/usr/bin/env bash
# Generated by podcast-to-essay web. Pipeline: split -> Step Plan ASR -> merge.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
node "\$HERE/../../web/server/transcribe.mjs" "\$HERE"
`;
}

function engineReady() {
  return !!(process.env.STEP_API_KEY || process.env.ANTHROPIC_AUTH_TOKEN);
}

function signalTranscription(task, signal) {
  if (process.platform !== 'win32' && task.child.pid) {
    process.kill(-task.child.pid, signal);
  } else {
    task.child.kill(signal);
  }
}

// ----------------------------- helpers --------------------------------------
async function titlesFromIndex() {
  const md = await readFileSafe(path.join(ROOT, 'INDEX.md'));
  const map = {};
  if (!md) return map;
  for (const line of md.split('\n')) {
    if (!line.startsWith('|')) continue;
    const cells = line.split('|').map((c) => c.trim());
    const slug = cells[1];
    const title = cells[2];
    const duration = cells[3];
    if (!slug || slug === 'slug' || /^-+$/.test(slug) || !SAFE_SLUG.test(slug)) continue;
    map[slug] = {
      title: title && title !== '标题' ? title : null,
      duration: duration && /^\d/.test(duration) ? duration : null,
    };
  }
  return map;
}

async function listEpisodes() {
  const titles = await titlesFromIndex();
  let entries = [];
  try {
    entries = await fsp.readdir(RAW, { withFileTypes: true });
  } catch {
    return [];
  }
  const dirs = entries.filter((e) => e.isDirectory()).map((e) => e.name);
  const out = [];
  for (const slug of dirs) {
    const dir = path.join(RAW, slug);
    let files = [];
    try { files = await fsp.readdir(dir); } catch { files = []; }
    const source = files.find((f) => /^source\./.test(f)) || null;
    const hasRaw = files.includes('asr_raw.txt');
    const hasSrt = files.includes('asr_raw.srt');
    let chunkFiles = files.filter((f) => /^chunk_\d+\.mp3$/.test(f));
    let completedChunkFiles = files.filter((f) => /^chunk_\d+\.txt$/.test(f));
    if (chunkFiles.length === 0) {
      try {
        const nested = await fsp.readdir(path.join(dir, 'chunks'));
        chunkFiles = nested.filter((f) => /^chunk_\d+\.mp3$/.test(f));
        completedChunkFiles = nested.filter((f) => /^chunk_\d+\.txt$/.test(f));
      } catch {}
    }
    const chunkCount = chunkFiles.length;
    const completedChunks = completedChunkFiles.length;
    let cleanedAt = null;
    try { const s = await fsp.stat(path.join(CLEANED, slug + '.md')); cleanedAt = s.mtimeMs; } catch {}
    const status = cleanedAt ? 'cleaned' : !source ? 'empty' : !hasRaw ? 'uploaded' : 'transcribed';
    const index = titles[slug] || {};
    const disk = await readMeta(dir);
    const article = await readJSON(path.join(dir, 'article-meta.json'));
    const task = TRANSCRIPTIONS.get(slug);
    let transcription = null;
    const savedState = await readJSON(path.join(dir, 'transcription-state.json'));
    if (task) {
      transcription = { state: task.paused ? 'paused' : 'running', error: null };
    } else if (savedState?.state === 'failed') {
      transcription = { state: 'failed', error: savedState.error || '转录没有完成，已保留完成的片段。' };
    }
    out.push({
      slug,
      title: index.title || disk?.title || disk?.originalName || null,
      duration: index.duration || null,
      source,
      sourceUrl: disk?.url || null,
      originalName: disk?.originalName || null,
      hasRaw,
      hasSrt,
      chunkCount,
      completedChunks,
      transcription,
      cleaned: !!cleanedAt,
      cleanedAt,
      article,
      status,
    });
  }
  out.sort((a, b) => b.slug.localeCompare(a.slug));
  return out;
}

async function readJSON(file) {
  const text = await readFileSafe(file);
  if (!text) return null;
  try { return JSON.parse(text); } catch { return null; }
}

function writeTranscriptionState(dir, state, error = null) {
  return fsp.writeFile(
    path.join(dir, 'transcription-state.json'),
    JSON.stringify({ state, error, updatedAt: Date.now() }),
    'utf8',
  ).catch(() => {});
}

function sendJSON(res, code, obj) {
  const data = JSON.stringify(obj);
  res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8', 'Access-Control-Allow-Origin': '*' });
  res.end(data);
}

function readFileSafe(p) {
  return fsp.readFile(p, 'utf8').catch(() => null);
}

function todayStamp() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

function slugBaseFromUrl(link) {
  const bv = String(link).match(/(BV[\w]{10})/i)?.[1];
  return `${todayStamp()}-${bv ? bv.toLowerCase() : 'link'}`;
}

async function uniqueSlug(base) {
  let slug = base;
  let n = 2;
  while (fs.existsSync(path.join(RAW, slug))) slug = `${base}-${n++}`;
  return slug;
}

function ingestFailure(err) {
  const detail = String(err?.message || '');
  if (err?.code === 'YTDLP_OUTDATED') {
    return { code: 'extractor_outdated', message: '下载组件需要更新。更新后再投这条链接。' };
  }
  if (/cookie|login|premium|unauthorized/i.test(detail)) {
    return { code: 'login_required', message: '这条视频需要 B站登录状态。请换本地文件，或稍后连接登录状态后重试。' };
  }
  if (/412|403|precondition|forbidden/i.test(detail)) {
    return { code: 'platform_refused', message: 'B站暂时没有接受这次读取。请稍后重试，或下载视频后拖进来。' };
  }
  if (/timeout|超时/i.test(detail)) {
    return { code: 'timeout', message: '读取时间过长，尚未拿到音频。请重试，或改为拖入本地文件。' };
  }
  return { code: 'download_failed', message: '没有拿到可转录的音频。请重试，或改为拖入本地文件。' };
}

function ingestProgress(line) {
  const text = String(line || '');
  if (/ExtractAudio|Destination:.*source\.mp3/i.test(text)) return '正在转换为 MP3…';
  const percent = text.match(/\[download\]\s+(\d+(?:\.\d+)?)%/i)?.[1];
  if (percent) return `正在下载音轨 · ${percent}%`;
  if (/Downloading video formats|Destination:.*source\./i.test(text)) return '正在下载音轨…';
  if (/Downloading webpage|Extracting URL|Downloading wbi sign/i.test(text)) return '正在读取视频信息…';
  return null;
}

// ----------------------------- routing ---------------------------------------
async function handleApi(req, res, url) {
  const parts = url.pathname.split('/').filter(Boolean); // ['api', ...]
  const method = req.method;

  // GET /api/health
  if (method === 'GET' && parts[1] === 'health') {
    return sendJSON(res, 200, { ok: true, engine: 'stepfun', root: ROOT, article: articleEngine });
  }

  // GET /api/episodes
  if (method === 'GET' && parts[1] === 'episodes' && parts.length === 2) {
    return sendJSON(res, 200, { episodes: await listEpisodes() });
  }

  // POST /api/ingests { url } -> SSE. A link becomes an episode only after an
  // audio file has landed, so a failed pull can never pollute raw/ or the queue.
  if (method === 'POST' && parts[1] === 'ingests' && parts.length === 2) {
    const body = await readBody(req);
    const link = String(body.url || '').trim();
    try { assertPublicHttpUrl(link); }
    catch (err) { return sendJSON(res, 400, { error: err.message }); }
    return streamIngest(res, link);
  }

  // POST /api/episodes  { slug }
  if (method === 'POST' && parts[1] === 'episodes' && parts.length === 2) {
    const body = await readBody(req);
    const slug = (body.slug || '').toString().trim();
    if (!SAFE_SLUG.test(slug)) return sendJSON(res, 400, { error: 'invalid slug' });
    const dir = path.join(RAW, slug);
    if (fs.existsSync(dir)) return sendJSON(res, 409, { error: 'episode exists' });
    await fsp.mkdir(dir, { recursive: true });
    await fsp.writeFile(path.join(dir, 'transcribe.sh'), transcribeTemplate(), 'utf8');
    await fsp.chmod(path.join(dir, 'transcribe.sh'), 0o755);
    return sendJSON(res, 201, { ok: true, slug });
  }

  // /api/episodes/:slug/...  (length >= 4)
  if (parts[1] === 'episodes' && parts.length >= 3) {
    const slug = parts[2];
    if (!SAFE_SLUG.test(slug)) return sendJSON(res, 400, { error: 'invalid slug' });
    const dir = path.join(RAW, slug);

    // DELETE /api/episodes/:slug
    if (method === 'DELETE' && parts.length === 3) {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'not found' });
      await fsp.rm(dir, { recursive: true, force: true });
      return sendJSON(res, 200, { ok: true });
    }

    // PATCH /api/episodes/:slug  { title }
    if (method === 'PATCH' && parts.length === 3) {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      const title = String((await readBody(req)).title || '').trim();
      if (!title) return sendJSON(res, 400, { error: '标题不能为空' });
      await writeMeta(dir, { ...(await readMeta(dir) || {}), title });
      return sendJSON(res, 200, { ok: true, title });
    }

    // POST /api/episodes/:slug/audio   (raw bytes; ASCII name in x-filename)
    if (method === 'POST' && parts[3] === 'audio') {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      const rawName = (req.headers['x-filename'] || 'source.mp3').toString();
      let fname = rawName;
      try { fname = decodeURIComponent(rawName); } catch {}
      const rawExt = path.extname(fname).toLowerCase();
      if (BLOCK_EXT.has(rawExt)) return sendJSON(res, 400, { error: '这不是音轨或视频' });
      const ext = extFromName(fname) || '.bin';
      await clearSourceFiles(dir);
      const dest = path.join(dir, 'source' + ext);
      await writeStreamToFile(req, dest);
      let originalName = '';
      try { originalName = decodeURIComponent(String(req.headers['x-original-name'] || '')); } catch {}
      await writeMeta(dir, {
        originalName: originalName || path.basename(fname),
        url: null,
        title: originalName ? originalName.replace(/\.[^.]+$/, '') : null,
      });
      return sendJSON(res, 200, { ok: true, file: path.basename(dest) });
    }

    // POST /api/episodes/:slug/from-url  { url } -> SSE
    if (method === 'POST' && parts[3] === 'from-url') {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      const body = await readBody(req);
      const link = String(body.url || '').trim();
      try { assertPublicHttpUrl(link); }
      catch (err) { return sendJSON(res, 400, { error: err.message }); }
      return streamFromUrl(res, link, dir);
    }

    // POST /api/episodes/:slug/transcription/pause|resume
    if (method === 'POST' && parts[3] === 'transcription' && (parts[4] === 'pause' || parts[4] === 'resume')) {
      const task = TRANSCRIPTIONS.get(slug);
      if (!task) return sendJSON(res, 409, { error: '这卷当前没有正在进行的转录。' });
      const paused = parts[4] === 'pause';
      if (task.paused === paused) return sendJSON(res, 200, { ok: true, paused });
      try {
        signalTranscription(task, paused ? 'SIGSTOP' : 'SIGCONT');
        task.paused = paused;
        await writeTranscriptionState(dir, paused ? 'paused' : 'running');
        task.emit('log', paused ? '⏸ 已暂停。素材和已完成的片段都留在这一卷。' : '▶ 继续转录…');
        return sendJSON(res, 200, { ok: true, paused });
      } catch {
        return sendJSON(res, 409, { error: '这次转录已经结束，无法再控制。' });
      }
    }

    // POST /api/episodes/:slug/transcribe  -> SSE log stream
    if (method === 'POST' && parts[3] === 'transcribe') {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      if (!engineReady()) return sendJSON(res, 409, { error: '还没有配置转录服务，暂时不能开始。' });
      if (TRANSCRIPTIONS.has(slug)) return sendJSON(res, 409, { error: '这卷正在转录。' });
      const script = path.join(dir, 'transcribe.sh');
      await fsp.writeFile(script, transcribeTemplate(), 'utf8');
      await fsp.chmod(script, 0o755);
      await writeTranscriptionState(dir, 'running');
      return streamTranscribe(res, script, dir);
    }

    // GET /api/episodes/:slug/transcript?type=raw|srt|cleaned
    if (method === 'GET' && parts[3] === 'transcript') {
      const type = url.searchParams.get('type') || 'raw';
      let p;
      if (type === 'srt') p = path.join(dir, 'asr_raw.srt');
      else if (type === 'cleaned') p = path.join(CLEANED, slug + '.md');
      else p = path.join(dir, 'asr_raw.txt');
      const text = await readFileSafe(p);
      if (text === null) return sendJSON(res, 404, { error: 'not found', type });
      res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8', 'Access-Control-Allow-Origin': '*' });
      return res.end(text);
    }

    // POST /api/episodes/:slug/clean — only writes a completed article after
    // the model response passes structural validation. There is no silent
    // heuristic fallback because that would mislabel a transcript as an article.
    if (method === 'POST' && parts[3] === 'clean') {
      const rawText = await readFileSafe(path.join(dir, 'asr_raw.txt'));
      if (rawText === null) return sendJSON(res, 404, { error: 'no asr_raw.txt' });
      const disk = await readMeta(dir);
      const index = (await titlesFromIndex())[slug] || {};
      try {
        const result = await generateArticle({ title: index.title || disk?.title || disk?.originalName || slug, rawText });
        const out = path.join(CLEANED, slug + '.md');
        const metaOut = path.join(dir, 'article-meta.json');
        const tempId = randomUUID();
        const outTemp = `${out}.${tempId}.tmp`;
        const metaTemp = `${metaOut}.${tempId}.tmp`;
        await Promise.all([
          fsp.writeFile(outTemp, result.text + '\n', 'utf8'),
          fsp.writeFile(metaTemp, JSON.stringify(result.meta, null, 2) + '\n', 'utf8'),
        ]);
        await fsp.rename(metaTemp, metaOut);
        await fsp.rename(outTemp, out);
        return sendJSON(res, 200, { ok: true, method: 'ai', ...result.meta });
      } catch (err) {
        console.error('[server] article generation failed:', err.message);
        return sendJSON(res, 502, { error: err.message || '文章整理失败，原稿仍然保留。' });
      }
    }
  }

  return sendJSON(res, 404, { error: 'not found' });
}

function streamFromUrl(res, link, dir) {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    'Access-Control-Allow-Origin': '*',
  });
  let closed = false;
  const emit = (event, data) => {
    res.write(`event: ${event}\n`);
    res.write(`data: ${String(data).replace(/\n/g, ' ')}\n\n`);
  };
  const finish = (code) => {
    if (closed) return;
    closed = true;
    emit('done', String(code));
    res.end();
  };
  res.on('close', () => { closed = true; });
  ingestUrl(link, dir, HOME, (line) => { if (!closed) emit('log', line); })
    .then(async (got) => {
      await writeMeta(dir, { url: link, title: got.title || null, originalName: got.title || got.file });
      emit('log', '✅ ' + (got.title || got.file));
      finish(0);
    })
    .catch((err) => {
      emit('log', '❌ ' + err.message);
      finish(1);
    });
}

function streamIngest(res, link) {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    'Access-Control-Allow-Origin': '*',
  });
  let closed = false;
  const emit = (event, data) => {
    if (closed) return;
    res.write(`event: ${event}\n`);
    res.write(`data: ${JSON.stringify(data)}\n\n`);
  };
  const finish = () => {
    if (closed) return;
    closed = true;
    res.end();
  };
  res.on('close', () => { closed = true; });

  const staged = path.join(INGESTS, randomUUID());
  void (async () => {
    try {
      await fsp.mkdir(staged, { recursive: true });
      emit('progress', { message: '正在读取视频信息…' });
      const got = await ingestUrl(link, staged, HOME, (line) => {
        const message = ingestProgress(line);
        if (message) emit('progress', { message });
      });
      const slug = await uniqueSlug(slugBaseFromUrl(link));
      await writeMeta(staged, { url: link, title: got.title || null, originalName: got.title || got.file });
      await fsp.writeFile(path.join(staged, 'transcribe.sh'), transcribeTemplate(), 'utf8');
      await fsp.chmod(path.join(staged, 'transcribe.sh'), 0o755);
      await fsp.rename(staged, path.join(RAW, slug));
      emit('ready', { slug, title: got.title || got.file });
    } catch (err) {
      await fsp.rm(staged, { recursive: true, force: true }).catch(() => {});
      emit('failed', ingestFailure(err));
    } finally {
      finish();
    }
  })();
}

function streamTranscribe(res, script, cwd) {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    'Access-Control-Allow-Origin': '*',
  });
  const child = spawn('bash', [script], {
    cwd,
    env: { ...process.env },
    detached: process.platform !== 'win32',
  });
  const slug = path.basename(cwd);
  let responseClosed = false;
  let finished = false;
  const emit = (event, data) => {
    if (responseClosed) return;
    res.write(`event: ${event}\n`);
    res.write(`data: ${data}\n\n`);
  };
  const task = { child, paused: false, emit, error: null };
  TRANSCRIPTIONS.set(slug, task);
  const onData = (buf) => {
    for (const line of buf.toString().split('\n')) {
      if (!line.length) continue;
      if (line.startsWith('❌')) task.error = line.replace(/^❌\s*/, '');
      emit('log', line);
    }
  };
  child.stdout.on('data', onData);
  child.stderr.on('data', onData);
  const finish = (code) => {
    if (finished) return;
    finished = true;
    TRANSCRIPTIONS.delete(slug);
    const exitCode = code ?? 1;
    void writeTranscriptionState(cwd, exitCode === 0 ? 'complete' : 'failed', task.error)
      .then(() => {
        emit('done', String(exitCode));
        if (!responseClosed) res.end();
      });
  };
  child.on('exit', (code) => finish(code ?? 1));
  child.on('error', (err) => {
    emit('log', '❌ ' + err.message);
    finish(1);
  });
  res.on('close', () => {
    // Closing the tab must not silently cancel a long transcription. The task
    // stays controllable through its pause/resume endpoints.
    responseClosed = true;
  });
}

function readBody(req) {
  return new Promise((resolve) => {
    let data = '';
    req.on('data', (c) => (data += c));
    req.on('end', () => {
      try { resolve(JSON.parse(data || '{}')); } catch { resolve({}); }
    });
  });
}

function writeStreamToFile(stream, dest) {
  return new Promise((resolve, reject) => {
    const ws = fs.createWriteStream(dest);
    stream.pipe(ws);
    ws.on('finish', resolve);
    ws.on('error', reject);
    stream.on('error', reject);
  });
}

// ----------------------------- static (prod) --------------------------------
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
};

function serveStatic(req, res, url) {
  let rel = decodeURIComponent(url.pathname);
  if (rel === '/') rel = '/index.html';
  const file = path.join(DIST, rel);
  if (!file.startsWith(DIST) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
    // SPA fallback
    const idx = path.join(DIST, 'index.html');
    if (fs.existsSync(idx)) {
      res.writeHead(200, { 'Content-Type': MIME['.html'] });
      return res.end(fs.readFileSync(idx));
    }
    return sendJSON(res, 404, { error: 'frontend not built; run `npm run build`' });
  }
  const ext = path.extname(file);
  res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
  res.end(fs.readFileSync(file));
}

// ----------------------------- server ---------------------------------------
const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, `http://localhost:${PORT}`);
    if (url.pathname.startsWith('/api/') || url.pathname === '/api') {
      await handleApi(req, res, url);
    } else if (!IS_DEV && fs.existsSync(DIST)) {
      serveStatic(req, res, url);
    } else {
      sendJSON(res, 404, { error: 'unknown route', hint: 'dev: use Vite on :5173; prod: build first' });
    }
  } catch (err) {
    sendJSON(res, 500, { error: err.message });
  }
});

server.listen(PORT, () => {
  console.log(`[server] podcast-to-essay backend on http://localhost:${PORT}`);
  console.log(`[server] root=${ROOT}`);
  console.log('[server] engine=StepFun ASR');
});
