// Podcast-to-Essay — Node backend (zero external dependencies).
//
// Responsibilities:
//  - Episode management: list / create / delete under <ROOT>/raw/<slug>/
//  - Audio upload: save uploaded file as raw/<slug>/source.<ext>
//  - Transcribe: spawn the per-episode transcribe.sh (ffmpeg + Step Plan ASR +
//    merge) and stream logs back over SSE
//  - Transcript read: serve raw/<slug>/asr_raw.{txt,srt} and cleaned/<slug>.md
//  - Clean: heuristic LLM-style cleanup of asr_raw.txt -> cleaned/<slug>.md
//    (the "Agent" hook — swap the cleanup step for a real model call later)
//
// In dev it only answers /api (Vite serves the frontend). In prod it also
// serves the built assets from ../dist.

import http from 'node:http';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { parseEnv } from 'node:util';
import {
  BLOCK_EXT,
  assertPublicHttpUrl,
  clearSourceFiles,
  extFromName,
  ingestUrl,
  readMeta,
  writeMeta,
} from './ingest.mjs';
import { articleConfig, generateArticle } from './article.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WEB_DIR = path.resolve(__dirname, '..');
const ROOT = path.resolve(process.env.DATA_ROOT || path.resolve(__dirname, '..', '..')); // podcast-to-essay
const RAW = path.join(ROOT, 'raw');
const CLEANED = path.join(ROOT, 'cleaned');
const INGESTS = path.join(ROOT, '.ingests');
const DIST = path.join(WEB_DIR, 'dist');

try {
  Object.assign(process.env, parseEnv(fs.readFileSync(path.join(ROOT, '.env.local'), 'utf8')));
} catch {}

const PORT = Number(process.env.PORT || 8787);
const LISTEN_HOST = process.env.HOST || '127.0.0.1';
const IS_DEV = process.env.IS_DEV === '1';
const ACCESS_PASSWORD = process.env.ACCESS_PASSWORD || '';
const SESSIONS = new Set();
const HOME = process.env.HOME || '';
const TRANSCRIPTIONS = new Map();
const MAX_UPLOAD_BYTES = Number(process.env.MAX_UPLOAD_BYTES || 512 * 1024 * 1024);
const MAX_JSON_BYTES = 1 * 1024 * 1024;

fs.mkdirSync(RAW, { recursive: true });
fs.mkdirSync(CLEANED, { recursive: true });
fs.mkdirSync(INGESTS, { recursive: true });

const SAFE_SLUG = /^[A-Za-z0-9._-]+$/;

let articleEngine = null;
try {
  const { model } = articleConfig();
  articleEngine = { provider: 'stepfun-token-plan', model };
} catch {}

// ---- per-episode transcribe.sh template (engine path injected at create) ----
const TRANSCRIBE_MJS = path.join(__dirname, 'transcribe.mjs');
function transcribeTemplate() {
  return `#!/usr/bin/env bash
# Generated by podcast-to-essay web. Pipeline: split -> Step Plan ASR -> merge.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
node "${TRANSCRIBE_MJS}" "$HERE"
`;
}

function engineReady() {
  return !!(process.env.STEP_API_KEY || process.env.ANTHROPIC_AUTH_TOKEN);
}

function signalTranscription(task, signal) {
  if (process.platform !== 'win32' && task.child.pid) {
    process.kill(-task.child.pid, signal);
  } else {
    task.child.kill(signal);
  }
}

// ----------------------------- helpers --------------------------------------
async function titlesFromIndex() {
  const md = await readFileSafe(path.join(ROOT, 'INDEX.md'));
  const map = {};
  if (!md) return map;
  for (const line of md.split('\n')) {
    if (!line.startsWith('|')) continue;
    const cells = line.split('|').map((c) => c.trim());
    const slug = cells[1];
    const title = cells[2];
    const duration = cells[3];
    if (!slug || slug === 'slug' || /^-+$/.test(slug) || !SAFE_SLUG.test(slug)) continue;
    map[slug] = {
      title: title && title !== '标题' ? title : null,
      duration: duration && /^\d/.test(duration) ? duration : null,
    };
  }
  return map;
}

async function listEpisodes() {
  const titles = await titlesFromIndex();
  let entries = [];
  try {
    entries = await fsp.readdir(RAW, { withFileTypes: true });
  } catch {
    return [];
  }
  const dirs = entries.filter((e) => e.isDirectory()).map((e) => e.name);
  const out = [];
  for (const slug of dirs) {
    const dir = path.join(RAW, slug);
    let files = [];
    try { files = await fsp.readdir(dir); } catch { files = []; }
    const source = files.find((f) => /^source\./.test(f)) || null;
    const hasRaw = files.includes('asr_raw.txt');
    const hasSrt = files.includes('asr_raw.srt');
    let chunkFiles = files.filter((f) => /^chunk_\d+\.mp3$/.test(f));
    let completedChunkFiles = files.filter((f) => /^chunk_\d+\.txt$/.test(f));
    if (chunkFiles.length === 0) {
      try {
        const nested = await fsp.readdir(path.join(dir, 'chunks'));
        chunkFiles = nested.filter((f) => /^chunk_\d+\.mp3$/.test(f));
        completedChunkFiles = nested.filter((f) => /^chunk_\d+\.txt$/.test(f));
      } catch {}
    }
    const chunkCount = chunkFiles.length;
    const completedChunks = completedChunkFiles.length;
    let cleanedAt = null;
    try { const s = await fsp.stat(path.join(CLEANED, slug + '.md')); cleanedAt = s.mtimeMs; } catch {}
    const status = cleanedAt ? 'cleaned' : !source ? 'empty' : !hasRaw ? 'uploaded' : 'transcribed';
    const index = titles[slug] || {};
    const disk = await readMeta(dir);
    const article = await readJSON(path.join(dir, 'article-meta.json'));
    const task = TRANSCRIPTIONS.get(slug);
    let transcription = null;
    const savedState = await readJSON(path.join(dir, 'transcription-state.json'));
    if (task) {
      transcription = { state: task.paused ? 'paused' : 'running', error: null };
    } else if (savedState?.state === 'failed') {
      transcription = { state: 'failed', error: savedState.error || '转录未完成，已完成的片段已保留。' };
    }
    out.push({
      slug,
      title: index.title || disk?.title || disk?.originalName || null,
      duration: index.duration || null,
      source,
      sourceUrl: disk?.url || null,
      originalName: disk?.originalName || null,
      hasRaw,
      hasSrt,
      chunkCount,
      completedChunks,
      transcription,
      cleaned: !!cleanedAt,
      cleanedAt,
      article,
      status,
    });
  }
  out.sort((a, b) => b.slug.localeCompare(a.slug));
  return out;
}

async function readJSON(file) {
  const text = await readFileSafe(file);
  if (!text) return null;
  try { return JSON.parse(text); } catch { return null; }
}

function writeTranscriptionState(dir, state, error = null) {
  return fsp.writeFile(
    path.join(dir, 'transcription-state.json'),
    JSON.stringify({ state, error, updatedAt: Date.now() }),
    'utf8',
  ).catch(() => {});
}

function corsOrigin(req) {
  const origin = String(req?.headers?.origin || '');
  if (!origin) return '';
  try {
    const u = new URL(origin);
    if (
      (u.protocol === 'http:' || u.protocol === 'https:') &&
      (u.hostname === 'localhost' || u.hostname === '127.0.0.1')
    ) {
      return origin;
    }
  } catch {}
  return '';
}

function corsHeaders(req) {
  const origin = corsOrigin(req);
  return origin ? { 'Access-Control-Allow-Origin': origin } : {};
}

function sendJSON(res, code, obj) {
  const data = JSON.stringify(obj);
  res.writeHead(code, {
    'Content-Type': 'application/json; charset=utf-8',
    ...corsHeaders(res.req),
  });
  res.end(data);
}

function readFileSafe(p) {
  return fsp.readFile(p, 'utf8').catch(() => null);
}

function todayStamp() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

function slugBaseFromUrl(link) {
  const bv = String(link).match(/(BV[\w]{10})/i)?.[1];
  return `${todayStamp()}-${bv ? bv.toLowerCase() : 'link'}`;
}

async function uniqueSlug(base) {
  let slug = base;
  let n = 2;
  while (fs.existsSync(path.join(RAW, slug))) slug = `${base}-${n++}`;
  return slug;
}

function ingestFailure(err) {
  const detail = String(err?.message || '');
  if (err?.code === 'YTDLP_OUTDATED') {
    return { code: 'extractor_outdated', message: 'yt-dlp 版本过旧，请更新后重试。' };
  }
  if (/cookie|login|premium|unauthorized/i.test(detail)) {
    return { code: 'login_required', message: '该视频需要 B 站登录。可改用本地文件，或配置 cookies 后重试。' };
  }
  if (/412|403|precondition|forbidden/i.test(detail)) {
    return { code: 'platform_refused', message: 'B 站拒绝了本次请求。请稍后重试，或改用本地文件。' };
  }
  if (/timeout|超时/i.test(detail)) {
    return { code: 'timeout', message: '下载超时。请重试，或改用本地文件。' };
  }
  return { code: 'download_failed', message: '未获取到可转录的音频。请重试，或改用本地文件。' };
}

function ingestProgress(line) {
  const text = String(line || '');
  if (/ExtractAudio|Destination:.*source\.mp3/i.test(text)) return '正在转换为 MP3…';
  const percent = text.match(/\[download\]\s+(\d+(?:\.\d+)?)%/i)?.[1];
  if (percent) return `正在下载音轨 · ${percent}%`;
  if (/Downloading video formats|Destination:.*source\./i.test(text)) return '正在下载音轨…';
  if (/Downloading webpage|Extracting URL|Downloading wbi sign/i.test(text)) return '正在读取视频信息…';
  return null;
}

// ----------------------------- access: owner vs guest -----------------------
// Owner = password session (or everyone when no password is configured).
// Guest = cookie-identified visitor with daily quotas, sees only own episodes.
const GUEST_LIMITS = {
  ingest: Number(process.env.GUEST_INGEST_PER_DAY || 5),
  transcribe: Number(process.env.GUEST_TRANSCRIBE_PER_DAY || 3),
  clean: Number(process.env.GUEST_CLEAN_PER_DAY || 3),
};

function sessionId(req) {
  const m = String(req.headers.cookie || '').match(/(?:^|;\s*)p2e_session=([^;]+)/);
  return m ? m[1] : '';
}

function isOwner(req) {
  return !ACCESS_PASSWORD || SESSIONS.has(sessionId(req));
}

function guestId(req, res) {
  const m = String(req.headers.cookie || '').match(/(?:^|;\s*)p2e_guest=([^;]+)/);
  if (m) return m[1];
  const id = randomUUID();
  res.setHeader('Set-Cookie', `p2e_guest=${id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${30 * 86400}`);
  return id;
}

// Quota keys embed the visitor IP, so they must not use the proxy address. Online the last hop
// is a Vercel edge node; only the first X-Forwarded-For entry is the real visitor. Direct
// requests have no XFF and fall back to the X-Real-IP nginx writes.
function clientIp(req) {
  const forwarded = String(req.headers['x-forwarded-for'] || '')
    .split(',')
    .map((part) => part.trim())
    .filter(Boolean);
  return forwarded[0] || String(req.headers['x-real-ip'] || '').trim() || req.socket.remoteAddress || '';
}

const QUOTA_FILE = path.join(ROOT, 'quota.json');
const QUOTA = new Map(); // key -> { date, ingest, transcribe, clean }

/** Only today's counters survive; the day rollover also drops stale keys. */
function pruneQuota() {
  const today = todayStamp();
  for (const [key, q] of QUOTA) if (!q || q.date !== today) QUOTA.delete(key);
}

async function loadQuota() {
  try {
    const saved = JSON.parse(await fsp.readFile(QUOTA_FILE, 'utf8'));
    const today = todayStamp();
    for (const [key, q] of Object.entries(saved)) {
      if (q && q.date === today) QUOTA.set(key, q);
    }
  } catch {
    // First run has no quota file yet.
  }
}

let quotaWritePending = null;
function persistQuota() {
  if (quotaWritePending) return;
  quotaWritePending = setTimeout(() => {
    quotaWritePending = null;
    pruneQuota();
    fsp.writeFile(QUOTA_FILE, JSON.stringify(Object.fromEntries(QUOTA), null, 2), 'utf8').catch(() => {});
  }, 500);
  quotaWritePending.unref?.();
}

function quotaEntry(key) {
  const today = todayStamp();
  let q = QUOTA.get(key);
  if (!q || q.date !== today) {
    q = { date: today, ingest: 0, transcribe: 0, clean: 0 };
    QUOTA.set(key, q);
  }
  return q;
}
function quotaLeft(key) {
  const q = quotaEntry(key);
  return {
    ingest: Math.max(0, GUEST_LIMITS.ingest - q.ingest),
    transcribe: Math.max(0, GUEST_LIMITS.transcribe - q.transcribe),
    clean: Math.max(0, GUEST_LIMITS.clean - q.clean),
  };
}
function quotaTake(req, gid, kind) {
  const key = `${clientIp(req)}|${gid}`;
  const left = quotaLeft(key);
  if (left[kind] <= 0) {
    return '游客每日额度已用完，明天再来。长期或大量使用建议自部署。';
  }
  quotaEntry(key)[kind]++;
  persistQuota();
  return null;
}

await loadQuota();

async function ownerOf(dir) {
  const m = await readJSON(path.join(dir, 'owner.json'));
  return m?.owner || 'user'; // entries without an owner file belong to the owner
}
async function canAccess(req, dir, gid) {
  if (isOwner(req)) return true;
  return (await ownerOf(dir)) === `guest:${gid}`;
}

// ----------------------------- routing ---------------------------------------
async function handleApi(req, res, url) {
  const parts = url.pathname.split('/').filter(Boolean); // ['api', ...]
  const method = req.method;

  // POST /api/login { password }
  if (method === 'POST' && parts[1] === 'login' && parts.length === 2) {
    const body = await readBody(req);
    if (!ACCESS_PASSWORD) return sendJSON(res, 200, { ok: true, locked: false });
    if (String(body.password || '') !== ACCESS_PASSWORD) return sendJSON(res, 401, { error: '密码不对' });
    const token = randomUUID();
    SESSIONS.add(token);
    res.setHeader('Set-Cookie', `p2e_session=${token}; Path=/; HttpOnly; SameSite=Lax`);
    return sendJSON(res, 200, { ok: true, locked: true });
  }

  // POST /api/logout
  if (method === 'POST' && parts[1] === 'logout' && parts.length === 2) {
    SESSIONS.delete(sessionId(req));
    res.setHeader('Set-Cookie', 'p2e_session=; Path=/; Max-Age=0');
    return sendJSON(res, 200, { ok: true });
  }

  // GET /api/health
  if (method === 'GET' && parts[1] === 'health') {
    const gid = guestId(req, res);
    return sendJSON(res, 200, {
      ok: true, locked: false, owner: isOwner(req),
      guest: { limits: GUEST_LIMITS, left: quotaLeft(`${clientIp(req)}|${gid}`) },
      engine: 'stepfun', root: ROOT, article: articleEngine,
    });
  }

  // GET /api/episodes
  if (method === 'GET' && parts[1] === 'episodes' && parts.length === 2) {
    const gid = guestId(req, res);
    const episodes = [];
    for (const ep of await listEpisodes()) {
      if (await canAccess(req, path.join(RAW, ep.slug), gid)) episodes.push(ep);
    }
    return sendJSON(res, 200, { episodes });
  }

  // POST /api/ingests { url } -> SSE. A link becomes an episode only after an
  // audio file has landed, so a failed pull can never pollute raw/ or the queue.
  if (method === 'POST' && parts[1] === 'ingests' && parts.length === 2) {
    const gid = guestId(req, res);
    const ownerTag = isOwner(req) ? 'user' : `guest:${gid}`;
    const body = await readBody(req);
    const link = String(body.url || '').trim();
    try { assertPublicHttpUrl(link); }
    catch (err) { return sendJSON(res, 400, { error: err.message }); }
    if (!isOwner(req)) {
      const err = quotaTake(req, gid, 'ingest');
      if (err) return sendJSON(res, 429, { error: err });
    }
    return streamIngest(res, link, ownerTag);
  }

  // POST /api/episodes  { slug } — guests import local files through this
  // route too: the episode is tagged guest:<gid>, counts against the ingest
  // quota, and stays invisible to other visitors.
  if (method === 'POST' && parts[1] === 'episodes' && parts.length === 2) {
    const gid = guestId(req, res);
    const body = await readBody(req);
    const slug = (body.slug || '').toString().trim();
    if (!SAFE_SLUG.test(slug)) return sendJSON(res, 400, { error: 'invalid slug' });
    const dir = path.join(RAW, slug);
    if (fs.existsSync(dir)) return sendJSON(res, 409, { error: 'episode exists' });
    if (!isOwner(req)) {
      const err = quotaTake(req, gid, 'ingest');
      if (err) return sendJSON(res, 429, { error: err });
    }
    await fsp.mkdir(dir, { recursive: true });
    await fsp.writeFile(path.join(dir, 'transcribe.sh'), transcribeTemplate(), 'utf8');
    await fsp.chmod(path.join(dir, 'transcribe.sh'), 0o755);
    if (!isOwner(req)) {
      await fsp.writeFile(path.join(dir, 'owner.json'), JSON.stringify({ owner: `guest:${gid}` }, null, 2), 'utf8');
    }
    return sendJSON(res, 201, { ok: true, slug });
  }

  // /api/episodes/:slug/...  (length >= 4)
  if (parts[1] === 'episodes' && parts.length >= 3) {
    const slug = parts[2];
    if (!SAFE_SLUG.test(slug)) return sendJSON(res, 400, { error: 'invalid slug' });
    const dir = path.join(RAW, slug);
    const gid = guestId(req, res);

    // Guests may only touch their own episodes (404 hides existence).
    if (!(await canAccess(req, dir, gid))) return sendJSON(res, 404, { error: 'not found' });

    // DELETE /api/episodes/:slug (owner only)
    if (method === 'DELETE' && parts.length === 3) {
      if (!isOwner(req)) return sendJSON(res, 403, { error: '仅所有者可删除。' });
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'not found' });
      await fsp.rm(dir, { recursive: true, force: true });
      return sendJSON(res, 200, { ok: true });
    }

    // PATCH /api/episodes/:slug  { title }
    if (method === 'PATCH' && parts.length === 3) {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      const title = String((await readBody(req)).title || '').trim();
      if (!title) return sendJSON(res, 400, { error: '标题不能为空' });
      await writeMeta(dir, { ...(await readMeta(dir) || {}), title });
      return sendJSON(res, 200, { ok: true, title });
    }

    // POST /api/episodes/:slug/audio   (raw bytes; ASCII name in x-filename;
    // guests may upload into episodes they created — canAccess already
    // constrains them to their own entries)
    if (method === 'POST' && parts[3] === 'audio') {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      const rawName = (req.headers['x-filename'] || 'source.mp3').toString();
      let fname = rawName;
      try { fname = decodeURIComponent(rawName); } catch {}
      const rawExt = path.extname(fname).toLowerCase();
      if (BLOCK_EXT.has(rawExt)) return sendJSON(res, 400, { error: '这不是音轨或视频' });
      const ext = extFromName(fname) || '.bin';
      await clearSourceFiles(dir);
      const dest = path.join(dir, 'source' + ext);
      await writeStreamToFile(req, dest);
      let originalName = '';
      try { originalName = decodeURIComponent(String(req.headers['x-original-name'] || '')); } catch {}
      await writeMeta(dir, {
        originalName: originalName || path.basename(fname),
        url: null,
        title: originalName ? originalName.replace(/\.[^.]+$/, '') : null,
      });
      return sendJSON(res, 200, { ok: true, file: path.basename(dest) });
    }

    // POST /api/episodes/:slug/from-url  { url } -> SSE
    if (method === 'POST' && parts[3] === 'from-url') {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      if (!isOwner(req)) {
        const err = quotaTake(req, gid, 'ingest');
        if (err) return sendJSON(res, 429, { error: err });
      }
      const body = await readBody(req);
      const link = String(body.url || '').trim();
      try { assertPublicHttpUrl(link); }
      catch (err) { return sendJSON(res, 400, { error: err.message }); }
      return streamFromUrl(res, link, dir);
    }

    // POST /api/episodes/:slug/transcription/pause|resume
    if (method === 'POST' && parts[3] === 'transcription' && (parts[4] === 'pause' || parts[4] === 'resume')) {
      const task = TRANSCRIPTIONS.get(slug);
      if (!task) return sendJSON(res, 409, { error: '当前没有进行中的转录。' });
      const paused = parts[4] === 'pause';
      if (task.paused === paused) return sendJSON(res, 200, { ok: true, paused });
      try {
        signalTranscription(task, paused ? 'SIGSTOP' : 'SIGCONT');
        task.paused = paused;
        await writeTranscriptionState(dir, paused ? 'paused' : 'running');
        task.emit('log', paused ? '已暂停。' : '继续转录…');
        return sendJSON(res, 200, { ok: true, paused });
      } catch {
        return sendJSON(res, 409, { error: '转录已结束。' });
      }
    }

    // POST /api/episodes/:slug/transcribe  -> SSE log stream
    if (method === 'POST' && parts[3] === 'transcribe') {
      if (!fs.existsSync(dir)) return sendJSON(res, 404, { error: 'episode not found' });
      if (!engineReady()) return sendJSON(res, 409, { error: '未配置转录服务，请先设置 STEP_API_KEY。' });
      if (TRANSCRIPTIONS.has(slug)) return sendJSON(res, 409, { error: '转录进行中。' });
      if (!isOwner(req)) {
        const err = quotaTake(req, gid, 'transcribe');
        if (err) return sendJSON(res, 429, { error: err });
      }
      const script = path.join(dir, 'transcribe.sh');
      await fsp.writeFile(script, transcribeTemplate(), 'utf8');
      await fsp.chmod(script, 0o755);
      await writeTranscriptionState(dir, 'running');
      return streamTranscribe(res, script, dir);
    }

    // GET /api/episodes/:slug/transcript?type=raw|srt|cleaned
    if (method === 'GET' && parts[3] === 'transcript') {
      const type = url.searchParams.get('type') || 'raw';
      let p;
      if (type === 'srt') p = path.join(dir, 'asr_raw.srt');
      else if (type === 'cleaned') p = path.join(CLEANED, slug + '.md');
      else p = path.join(dir, 'asr_raw.txt');
      const text = await readFileSafe(p);
      if (text === null) return sendJSON(res, 404, { error: 'not found', type });
      res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8', ...corsHeaders(req) });
      return res.end(text);
    }

    // POST /api/episodes/:slug/clean — only writes a completed article after
    // the model response passes structural validation. There is no silent
    // heuristic fallback because that would mislabel a transcript as an article.
    if (method === 'POST' && parts[3] === 'clean') {
      if (!isOwner(req)) {
        const err = quotaTake(req, gid, 'clean');
        if (err) return sendJSON(res, 429, { error: err });
      }
      const rawText = await readFileSafe(path.join(dir, 'asr_raw.txt'));
      if (rawText === null) return sendJSON(res, 404, { error: 'no asr_raw.txt' });
      const disk = await readMeta(dir);
      const index = (await titlesFromIndex())[slug] || {};
      try {
        const result = await generateArticle({ title: index.title || disk?.title || disk?.originalName || slug, rawText });
        const out = path.join(CLEANED, slug + '.md');
        const metaOut = path.join(dir, 'article-meta.json');
        const tempId = randomUUID();
        const outTemp = `${out}.${tempId}.tmp`;
        const metaTemp = `${metaOut}.${tempId}.tmp`;
        await Promise.all([
          fsp.writeFile(outTemp, result.text + '\n', 'utf8'),
          fsp.writeFile(metaTemp, JSON.stringify(result.meta, null, 2) + '\n', 'utf8'),
        ]);
        await fsp.rename(metaTemp, metaOut);
        await fsp.rename(outTemp, out);
        return sendJSON(res, 200, { ok: true, method: 'ai', ...result.meta });
      } catch (err) {
        console.error('[server] article generation failed:', err.message);
        return sendJSON(res, 502, { error: err.message || '文章整理失败，原稿保留。' });
      }
    }
  }

  return sendJSON(res, 404, { error: 'not found' });
}

function streamFromUrl(res, link, dir) {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    ...corsHeaders(res.req),
  });
  let closed = false;
  const emit = (event, data) => {
    res.write(`event: ${event}\n`);
    res.write(`data: ${String(data).replace(/\n/g, ' ')}\n\n`);
  };
  const finish = (code) => {
    if (closed) return;
    closed = true;
    emit('done', String(code));
    res.end();
  };
  res.on('close', () => { closed = true; });
  ingestUrl(link, dir, HOME, (line) => { if (!closed) emit('log', line); })
    .then(async (got) => {
      await writeMeta(dir, { url: link, title: got.title || null, originalName: got.title || got.file });
      emit('log', got.title || got.file);
      finish(0);
    })
    .catch((err) => {
      emit('log', err.message);
      finish(1);
    });
}

function streamIngest(res, link, ownerTag = 'user') {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    ...corsHeaders(res.req),
  });
  let closed = false;
  const emit = (event, data) => {
    if (closed) return;
    res.write(`event: ${event}\n`);
    res.write(`data: ${JSON.stringify(data)}\n\n`);
  };
  const finish = () => {
    if (closed) return;
    closed = true;
    res.end();
  };
  res.on('close', () => { closed = true; });

  const staged = path.join(INGESTS, randomUUID());
  void (async () => {
    try {
      await fsp.mkdir(staged, { recursive: true });
      emit('progress', { message: '正在读取视频信息…' });
      const got = await ingestUrl(link, staged, HOME, (line) => {
        const message = ingestProgress(line);
        if (message) emit('progress', { message });
      });
      const slug = await uniqueSlug(slugBaseFromUrl(link));
      await writeMeta(staged, { url: link, title: got.title || null, originalName: got.title || got.file });
      await fsp.writeFile(path.join(staged, 'transcribe.sh'), transcribeTemplate(), 'utf8');
      await fsp.chmod(path.join(staged, 'transcribe.sh'), 0o755);
      await fsp.writeFile(path.join(staged, 'owner.json'), JSON.stringify({ owner: ownerTag }, null, 2), 'utf8');
      await fsp.rename(staged, path.join(RAW, slug));
      emit('ready', { slug, title: got.title || got.file });
    } catch (err) {
      await fsp.rm(staged, { recursive: true, force: true }).catch(() => {});
      emit('failed', ingestFailure(err));
    } finally {
      finish();
    }
  })();
}

function streamTranscribe(res, script, cwd) {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    ...corsHeaders(res.req),
  });
  const child = spawn('bash', [script], {
    cwd,
    env: { ...process.env },
    detached: process.platform !== 'win32',
  });
  const slug = path.basename(cwd);
  let responseClosed = false;
  let finished = false;
  const emit = (event, data) => {
    if (responseClosed) return;
    res.write(`event: ${event}\n`);
    res.write(`data: ${data}\n\n`);
  };
  const task = { child, paused: false, emit, error: null };
  TRANSCRIPTIONS.set(slug, task);
  const onData = (buf) => {
    for (const line of buf.toString().split('\n')) {
      if (!line.length) continue;
      if (line.startsWith('❌')) task.error = line.replace(/^❌\s*/, '');
      emit('log', line);
    }
  };
  child.stdout.on('data', onData);
  child.stderr.on('data', onData);
  const finish = (code) => {
    if (finished) return;
    finished = true;
    TRANSCRIPTIONS.delete(slug);
    const exitCode = code ?? 1;
    void writeTranscriptionState(cwd, exitCode === 0 ? 'complete' : 'failed', task.error)
      .then(() => {
        emit('done', String(exitCode));
        if (!responseClosed) res.end();
      });
  };
  child.on('exit', (code) => finish(code ?? 1));
  child.on('error', (err) => {
    emit('log', '❌ ' + err.message);
    finish(1);
  });
  res.on('close', () => {
    // Closing the tab must not silently cancel a long transcription. The task
    // stays controllable through its pause/resume endpoints.
    responseClosed = true;
  });
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    let seen = 0;
    req.on('data', (c) => {
      seen += c.length;
      if (seen > MAX_JSON_BYTES) {
        reject(new Error('request body too large'));
        req.destroy();
        return;
      }
      data += c;
    });
    req.on('end', () => {
      try { resolve(JSON.parse(data || '{}')); } catch { resolve({}); }
    });
    req.on('error', reject);
  });
}

function writeStreamToFile(stream, dest) {
  return new Promise((resolve, reject) => {
    const ws = fs.createWriteStream(dest);
    let seen = 0;
    let failed = false;
    const fail = (err) => {
      if (failed) return;
      failed = true;
      stream.unpipe(ws);
      ws.destroy();
      stream.destroy?.();
      fsp.rm(dest, { force: true }).finally(() => reject(err));
    };
    stream.on('data', (chunk) => {
      seen += chunk.length;
      if (seen > MAX_UPLOAD_BYTES) fail(new Error('文件太大'));
    });
    stream.pipe(ws);
    ws.on('finish', () => { if (!failed) resolve(); });
    ws.on('error', fail);
    stream.on('error', fail);
  });
}

// ----------------------------- static (prod) --------------------------------
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
};

function serveStatic(req, res, url) {
  let rel = decodeURIComponent(url.pathname);
  if (rel === '/') rel = '/index.html';
  const file = path.join(DIST, rel);
  if (!file.startsWith(DIST) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
    // SPA fallback
    const idx = path.join(DIST, 'index.html');
    if (fs.existsSync(idx)) {
      res.writeHead(200, { 'Content-Type': MIME['.html'] });
      return res.end(fs.readFileSync(idx));
    }
    return sendJSON(res, 404, { error: 'frontend not built; run `npm run build`' });
  }
  const ext = path.extname(file);
  res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
  res.end(fs.readFileSync(file));
}

// ----------------------------- server ---------------------------------------
const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, `http://localhost:${PORT}`);
    if (req.method === 'OPTIONS') {
      res.writeHead(204, {
        ...corsHeaders(req),
        'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, x-filename, x-original-name',
      });
      return res.end();
    }
    if (url.pathname.startsWith('/api/') || url.pathname === '/api') {
      await handleApi(req, res, url);
    } else if (!IS_DEV && fs.existsSync(DIST)) {
      serveStatic(req, res, url);
    } else {
      sendJSON(res, 404, { error: 'unknown route', hint: 'dev: use Vite on :5173; prod: build first' });
    }
  } catch (err) {
    const code = err && err.message === 'request body too large' ? 413 : 500;
    sendJSON(res, code, { error: err.message });
  }
});

server.listen(PORT, LISTEN_HOST, () => {
  console.log(`[server] podcast-to-essay backend on http://${LISTEN_HOST}:${PORT}`);
  console.log(`[server] root=${ROOT}`);
  console.log('[server] engine=StepFun ASR');
});
